import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:hive/hive.dart';

part 'message.g.dart'; // Will be generated by Hive

@HiveType(typeId: 0)
class Message {
  @HiveField(0)
  final String id;
  
  @HiveField(1)
  final String senderId;
  
  @HiveField(2)
  final String content;
  
  @HiveField(3)
  final DateTime timestamp;
  
  @HiveField(4)
  final bool isCommand;
  
  @HiveField(5)
  final MessageStatus status;

  Message({
    required this.id,
    required this.senderId,
    required this.content,
    required this.timestamp,
    this.isCommand = false,
    this.status = MessageStatus.sent,
  });

  factory Message.fromJson(Map<String, dynamic> json) {
    return Message(
      id: json['id'] as String,
      senderId: json['senderId'] as String,
      content: json['content'] as String,
      timestamp: (json['timestamp'] as Timestamp).toDate(),
      isCommand: json['isCommand'] as bool? ?? false,
      status: MessageStatus.values.firstWhere(
        (e) => e.toString() == json['status'],
        orElse: () => MessageStatus.sent,
      ),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'senderId': senderId,
      'content': content,
      'timestamp': Timestamp.fromDate(timestamp),
      'isCommand': isCommand,
      'status': status.toString(),
    };
  }
}

@HiveType(typeId: 1)
enum MessageStatus {
  @HiveField(0)
  sent,
  @HiveField(1)
  delivered,
  @HiveField(2)
  read,
  @HiveField(3)
  failed
}
