// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRJ5Mf4fJVbcnll_t3MwjfHBXfPJxFlvs',
    appId: '1:453713187164:web:73cecd7f38b52b7e6f7199',
    messagingSenderId: '453713187164',
    projectId: 'bt-term-417bc',
    authDomain: 'bt-term-417bc.firebaseapp.com',
    storageBucket: 'bt-term-417bc.firebasestorage.app',
    measurementId: 'G-Z18QBZ7RKY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVys-0ABat98cW4mRI3RV3F2PXnX01NUw',
    appId: '1:453713187164:android:fde9ebb65c1dbc066f7199',
    messagingSenderId: '453713187164',
    projectId: 'bt-term-417bc',
    storageBucket: 'bt-term-417bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBceNLSkI46qXXHwuPo_XxeWQqCCWQ1bT8',
    appId: '1:453713187164:ios:eca3d374361d97c96f7199',
    messagingSenderId: '453713187164',
    projectId: 'bt-term-417bc',
    storageBucket: 'bt-term-417bc.firebasestorage.app',
    iosBundleId: 'com.example.bdTerminal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBceNLSkI46qXXHwuPo_XxeWQqCCWQ1bT8',
    appId: '1:453713187164:ios:eca3d374361d97c96f7199',
    messagingSenderId: '453713187164',
    projectId: 'bt-term-417bc',
    storageBucket: 'bt-term-417bc.firebasestorage.app',
    iosBundleId: 'com.example.bdTerminal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRJ5Mf4fJVbcnll_t3MwjfHBXfPJxFlvs',
    appId: '1:453713187164:web:8d843eb5fa6f4e706f7199',
    messagingSenderId: '453713187164',
    projectId: 'bt-term-417bc',
    authDomain: 'bt-term-417bc.firebaseapp.com',
    storageBucket: 'bt-term-417bc.firebasestorage.app',
    measurementId: 'G-ETYKC2ZEDY',
  );
}
